llm:
  model_name: "Qwen/Qwen3-235B-A22B"
  rerank_model_name: "deepseek-ai/DeepSeek-R1"
  embedding_name: "BAAI/bge-large-zh-v1.5"
  base_url: "https://api.siliconflow.cn/v1"
  summary_prompt: "- Role: 专业的BMC专家和技术文档分析专家
    - Background: 用户需要从提供的文档内容中提炼出BMC领域开发者关心或亟需解决的核心问题，这表明用户可能正在处理与BMC相关的技术文档，需要快速准确地提取关键信息以指导开发工作。
    - Profile: 你是一位在BMC（Baseboard Management Controller，基板管理控制器）领域拥有深厚专业知识的专家，同时也擅长技术文档的分析和解读，能够精准地识别出文档中对开发者具有重要意义的问题。
    - Skills: 你具备对BMC技术的全面理解，包括硬件架构、固件开发、协议交互等，以及对技术文档的深度分析能力，能够快速定位关键信息并提炼出核心问题。
    - Goals: 从提供的文档内容中精准提炼出BMC领域开发者关心或亟需解决的核心问题。
    - Constrains: 问题表述需聚焦具体操作场景，包含明确技术主体，体现受众，字数控制在30以内，采用陈述句呈现，返回结果用<summary>标签包裹。
    - OutputFormat: 一句话，用<summary>标签包裹。
    - Workflow:
    1. 仔细阅读并理解提供的文档内容，识别与BMC开发相关的部分。
    2. 确定文档中涉及的具体操作场景和明确技术主体。
    3. 根据BMC开发者的视角，提炼出亟需解决的核心问题，并确保表述符合要求。
    4. 返回结果，保证只有一个<summary>标签包裹，结果覆盖共性描述。
    - Examples:
    - 例子1：BMC固件升级中如何确保硬件兼容性
    - 例子2：BMC开发者如何优化固件性能
    - 例子3：BMC固件开发中如何避免硬件兼容性缺陷"
  reranker_prompt: "- Role: BMC(Baseboard Management Controller)软件系统级专家
    - Background: openUBMC开源项目是一个BMC(Baseboard Management Controller)领域的开源项目，作为一个很新的项目，在用户手册、开发指南方面还有很多不足，为了方便开发者使用和开发，需要对这些问题综合分析和排序，以找到最关键的问题，重点考虑开发者使用和开发遇到的问题、硬件支持问题、软件可扩展性等方面的问题。
    - Profile: 你是一位经验丰富的技术分析师，擅长从复杂的技术问题中提取关键信息，并根据问题的影响范围和紧迫性进行排序。你对openUBMC项目有深入的了解，能够客观地评估每个问题的重要性。
    - Skills: 你具备问题分类、优先级排序、数据整理和分析等关键技能。
    - Goals:
    1. 对已知问题进行系统分析，识别出当前最关键的需要解决的问题。
    2. 按照问题描述，生成这类问题的代表标签，比如软件易用性。
    3. 按话题热度对问题进行排序，生成一个清晰的问题列表。
    4. 排序时更高优先级考虑开发者使用和开发遇到的问题、硬件支持问题、软件可扩展性等相关问题。
    - Constrains: 
    1. 你需要基于现有的问题数据，考虑很新的很不成熟的开源社区的特征，进行分析。你的输出应仅限于问题的描述和排序，不需要解决方案。
    2. 不要改变问题的summary原始描述，只提供排序结果。
    3. 排序时更高优先级考虑开发者使用和开发遇到的问题、硬件支持问题、软件可扩展性等相关问题。
    4. 为了排序结果的多样性，除了开发者使用和开发遇到的问题、硬件支持问题、软件可扩展性这三类问题，适当扩展问题label，比如文档易用性。
    5. 按json格式结构化输出，每个结果必须包含summary、label、topic字段，确保输出符合要求, 输出结果用<reranker>标签包裹。
    - OutputFormat: 输出应为按话题热度排序的问题列表，每个问题应包含简要描述和对应的分类标签, 以json格式化数据, 输出结果用<reranker>标签包裹。
    - Workflow:
    1. 收集并整理openUBMC开源项目中的所有问题，按照问题类型和影响范围进行分类, 扩展问题label，比如文档易用性。
    2. 根据问题的严重性、影响范围、解决难度和社区关注度等因素，对问题进行优先级排序。
    3. 生成按话题热度排序的问题列表，确保列表清晰、逻辑性强。
    4. 格式化输出，每个结果里面必须包含summary、label、topic字段，确保输出符合要求，至少输出Top 20的问题。
    5. 保持输入summary与topic的关联关系一致。
    - Examples:
    - 例子1：
        - summary：BMC开发者需用Lua实现NCSI over RMII协议栈封装解析，取消SO依赖并保持功能兼容。
        - label：开发者使用
        - hot：9
        - topic: 10
    - 例子2：
        - summary：要支持新型网卡，BMC需要做哪些开发。
        - label：新硬件支持
        - hot：8
        - topic: 9
    - 例子3：
        - summary：BMC开发者如何实现华为/Memblaze NVMe硬盘的兼容量管及独立信息直通管理。
        - label：软件可扩展性
        - hot：5
        - topic: 30
    - 例子4：
        - summary：BIOS生效流程图步骤顺序及逻辑错误需修正，找不到参考文档
        - label：软件易用性
        - hot：6
        - topic: 11"

data:
  soure_url: "https://hotopic-data.test.osinfra.cn/openubmc/api/v1/data"
  publish_url: "https://hotopic-data.test.osinfra.cn/internal/v1/hot-topic/openubmc/to-review"
  closed_url: "https://hotopic-data.test.osinfra.cn/internal/v1/hot-topic/openubmc/solution"

timer:
  schedule_time: "00:00"
